dependencies:
 - numpy>=1.26
 - nibabel
 - pydicom==3.*;python_version>="3.10"
 - pydicom==2.4.*;python_version<"3.10"
 - pyMapVBVD>=0.6.0
 - scipy>=1.13
 - brukerapi>=0.1.8,<0.1.9
 - pandas
 - nifti-mrs>=1.3.2
 - chardet
