dependencies:
 - numpy>=1.26
 - nibabel
 - pydicom==3.*
 - pyMapVBVD>=0.6.0
 - scipy>=1.13
 - brukerapi>=0.2.2
 - pandas
 - nifti-mrs>=1.3.2
 - textual>=7.4.0,<8
#  - pip
#  - pip:
#     - "brukerapi @ git+https://github.com/VKarlaftis/brukerapi-python"
