name: Run code tests on push and pull requests
on:
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  push-tests:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    name: Pixi (py312, ubuntu-latest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
          lfs: true
      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          manifest-path: pyproject.toml
          environments: py312
          cache: false
          activate-environment: false
      - name: Lint
        run: |
          pixi run lint
      - name: Run pytest
        run: |
          pixi run -e py312 test

  pr-tests:
    if: github.event_name == 'pull_request'
    name: Pixi (${{ matrix.environment }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        environment: ["py310", "py311", "py313", "py314"]
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
          lfs: true
      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          manifest-path: pyproject.toml
          environments: ${{ matrix.environment }}
          cache: false
          activate-environment: false
      - name: Lint
        if: matrix.environment == 'py312'
        run: |
          pixi run lint
      - name: Run pytest
        run: |
          pixi run -e ${{ matrix.environment }} test
